language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest -v *_tests.py
deploy:
  provider: heroku
  api_key:
    secure: Rxh+Z8EaBQ4WdUmbkh3qsXrAeQEMh1tCgdfxGdN88kcpp1tZ7flK1gVrpXCMXf8Lcsv4yIq76CDfqkyx1fGISKkZpyohjz0ZdVPWLN2VUiMATTDPaYD3BmJcLDvJ5A5cswJP2X4XogOC9t4i0m0HNu+U6Xxi4BVy1C48fW3wwQtbhm6dfl+Oly6gZI/thXo1kB2OAqtAwnlC80fSnTPYUkPnR21nKY+kV8womfARRSjzHRhcVz5zOOE4ODFDkmQPV2WFJF5P3/581Dl+KbYpRf3D8yX+A5vL8+3yVw5CZd6t59NbMsGIB0FgNC+UvQbWjobEGvq4bsHw/MQQAl3eB2rc61tT9CnY6xOGFFXGt2ChOinwRv8GXBr8tFIWPo0lQPaF9tPgztIhKiSK76xsW6bUMdF1ODLvsjyVaeQq4g3SUPm5hm9SPw/rY7dI2BWR/zpmkGvydDn5xcLkLxmv1BCWxLUHoFGTUrHRD4C1fyBOZWhZbEphrrMAphhH4RTVOG+/2Lb5T+9DBfSoHdriXYt9GuydD9IBRSAI0f1sImZqqD0+W6083xv0b27bzBpZ0dttYqrRKCyVhoS5GoCY6gIiCjMzzZ2lGS/QYaIJO9f9OCtLKNb3UZEnJIoaR/mUq0xwpV7DQMlZNv1JkGM82W7atV+Hc3crLyAWMS7wpvA=
