language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest -v *_tests.py
deploy:
  provider: heroku
  api_key:
    secure: JaMAr++wFWMqBQWwAyktxWx7ulPZqhnzg2rU4CXy2iTQSbLu6v8kfgYcwpY/kMUS0f+r+P5DMZ+gD0d9N5YhvVQJ/CawOOXIC+pSR9PVAXX9M6JiJtJjqrn1p7gJOCErAnsSNaQ2ePVuHz194P8L5l/seNj78z6UzsjVVUcoOzOO7fBtLOxzKscpL+hM/tegGo55YANuQwVWo8dfqQq8CSmPeTwAwF9+05GROQbCbAFjNy9jo0se6R2nOx8OmStrEEaJoyoMUI2tq3Plq8kEVf4RyeY3kyhaYZ6k7HsonJIJXfh4saW5TBcZznTLbFvMOJiI+khrKlJ8kIrfajS0AaVBEkM1ZLE9rqiCvIpzrZTDY9Oe2zgDPvD8BM1q04y3VbawAA/jD0qMmuzSyC+1OPOKL4GKYIxiukn4z9WGVrP3SFOk9/px33U/L/WrDXSpbbwIegzfsr7Qa2Qr1GV137rCsBIdQWot0AJBlg+XvCagVBbMdHODbEhBGyPKYTEIQCyWjf09lwhkv4NEvJrFsApeuKg2MEvGuPhQTldot1lGRX8oSbMgei2P6xjp7dXJlGgX67EcLt2BqvXLLf6ivX9BflJmugpQOSwEGMBY+IM7QD3I7NjTmws7xH6dbXMhFSWI9wSDOZ/lacJtt/q+MGn566+/skGTfTXmn0h/iXk=
